server:
  port: 8001
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  application:
    name: producer-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root123
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
    ####spring boot 整合 springData jpa 报错解决
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    ####spring boot 整合 springData jpa 报错解决
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

